---
abstract: 'Portably access the process table'
author:
  - 'Brendan Byrd <BBYRD@CPAN.org>'
build_requires:
  Devel::SimpleTrace: 0.07
  ExtUtils::MakeMaker: 6.31
  File::Spec: 3.16
  Test::CheckDeps: 0.010
  Test::More: 0.94
  Test::Most: 0.01
  perl: v5.8.8
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.040, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: P9Y-ProcessTable
no_index:
  directory:
    - corpus
    - examples
    - t
    - xt
provides:
  P9Y::ProcessTable:
    file: lib/P9Y/ProcessTable.pm
    version: 1.08
  P9Y::ProcessTable::Process:
    file: lib/P9Y/ProcessTable/Process.pm
    version: 1.08
  P9Y::ProcessTable::Process::Base:
    file: lib/P9Y/ProcessTable/Process/Base.pm
    version: 1.08
  P9Y::ProcessTable::Role::Process::OS::MSWin32:
    file: lib/P9Y/ProcessTable/Role/Process/OS/MSWin32.pm
    version: 1.08
  P9Y::ProcessTable::Role::Table::OS::MSWin32:
    file: lib/P9Y/ProcessTable/Role/Table/OS/MSWin32.pm
    version: 1.08
  P9Y::ProcessTable::Role::Table::OS::VMS:
    file: lib/P9Y/ProcessTable/Role/Table/OS/VMS.pm
    version: 1.08
  P9Y::ProcessTable::Role::Table::OS::freebsd:
    file: lib/P9Y/ProcessTable/Role/Table/OS/freebsd.pm
    version: 1.08
  P9Y::ProcessTable::Role::Table::OS::os2:
    file: lib/P9Y/ProcessTable/Role/Table/OS/os2.pm
    version: 1.08
  P9Y::ProcessTable::Role::Table::PPT:
    file: lib/P9Y/ProcessTable/Role/Table/PPT.pm
    version: 1.08
  P9Y::ProcessTable::Role::Table::ProcFS:
    file: lib/P9Y/ProcessTable/Role/Table/ProcFS.pm
    version: 1.08
  P9Y::ProcessTable::Table:
    file: lib/P9Y/ProcessTable/Table.pm
    version: 1.08
  P9Y::ProcessTable::Table::Base:
    file: lib/P9Y/ProcessTable/Table/Base.pm
    version: 1.08
requires:
  List::AllUtils: 0
  Module::Runtime: 0.002
  Moo: 0.009001
  Path::Class: 0.32
  namespace::clean: 0
  perl: v5.8.8
resources:
  IRC: irc://irc.perl.org/#win32
  bugtracker: https://github.com/SineSwiper/P9Y-ProcessTable/issues
  homepage: https://github.com/SineSwiper/P9Y-ProcessTable
  repository: https://github.com/SineSwiper/P9Y-ProcessTable.git
version: 1.08
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::Meta::Dynamic::Config
      name: Meta::Dynamic::Config
      version: 0.04
    -
      class: inc::P9YOSDeps
      config:
        Dist::Zilla::Plugin::MakeMaker::Awesome:
          version: 0.35
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: P9YOSDeps
      version: ~
    -
      class: Dist::Zilla::Plugin::ReportPhase
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Author::BBYRD/ReportPhase'
      version: 0.03
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::BBYRD/Authority'
      version: 1.009
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: 0.90
          version_by_branch: 0
          version_regexp: '(?^:^v(.+)$)'
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
      name: '@Author::BBYRD/Git::NextVersion'
      version: 2.036
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory: []
          root: '.'
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: 0
      name: '@Author::BBYRD/Git::GatherDir'
      version: 2.036
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@Author::BBYRD/OurPkgVersion'
      version: 0.06
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit::CPAN::Changes
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
      name: '@Author::BBYRD/ChangelogFromGit::CPAN::Changes'
      version: 0.108
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::BBYRD/PruneCruft'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::BBYRD/ManifestSkip'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::BBYRD/Manifest'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::BBYRD/License'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::BBYRD/ReadmePodInRoot'
      version: 0.150250
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::BBYRD/ReadmeTextInBuild'
      version: 0.150250
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::BBYRD/ReadmeHTMLInBuild'
      version: 0.150250
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::BBYRD/InstallGuide'
      version: 1.200006
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::BBYRD/ExecDir'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@Author::BBYRD/@TestingMania/Test::UnusedVars'
      version: 2.000007
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: '@Author::BBYRD/@TestingMania/Test::Synopsis'
      version: 2.000004
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Author::BBYRD/@TestingMania/Test::Portability'
      version: 2.000006
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::BBYRD/@TestingMania/Test::CPAN::Changes'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@Author::BBYRD/@TestingMania/Test::CPAN::Meta::JSON'
      version: 0.004
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Author::BBYRD/@TestingMania/Test::DistManifest'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/author/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: '@Author::BBYRD/@TestingMania/Test::NoTabs'
      version: 0.15
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::BBYRD/@TestingMania/Test::MinimumVersion'
      version: 2.000006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::BBYRD/@TestingMania/PodSyntaxTests'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: '@Author::BBYRD/@TestingMania/MojibakeTests'
      version: 0.8
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Author::BBYRD/RunExtraTests'
      version: 0.028
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
          trailing_whitespace: 0
      name: '@Author::BBYRD/Test::EOL'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      config:
        Dist::Zilla::Plugin::Test::CheckDeps:
          fatal: 0
          filename: t/00-check-deps.t
          level: classic
          todo_when: 0
      name: '@Author::BBYRD/Test::CheckDeps'
      version: 0.013
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Author::BBYRD/Test::ReportPrereqs'
      version: 0.021
    -
      class: Dist::Zilla::Plugin::Test::CheckManifest
      name: '@Author::BBYRD/Test::CheckManifest'
      version: 0.04
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Author::BBYRD/CheckPrereqsIndexed'
      version: 0.016
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::BBYRD/MetaConfig'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::BBYRD/MetaJSON'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::BBYRD/MetaYAML'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::BBYRD/MetaNoIndex'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::BBYRD/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: 5.040
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: '@Author::BBYRD/MetaProvides::Package'
      version: 2.003001
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::BBYRD/GithubMeta'
      version: 0.54
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: '@Author::BBYRD/ContributorsFromGit'
      version: 0.017
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@Author::BBYRD/MetaResources'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::BBYRD/CopyFilesFromBuild'
      version: 0.151680
    -
      class: Dist::Zilla::Plugin::TravisYML
      name: '@Author::BBYRD/TravisYML'
      version: 1.15
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
      name: '@Author::BBYRD/Git::CheckFor::CorrectBranch'
      version: 0.013
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: ''
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: 0
          release_branch: build/%b
          release_message: 'Release build of v%v (on %b)'
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
      name: '@Author::BBYRD/Git::CommitBuild'
      version: 2.036
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - '.travis.yml'
            - README.pod
            - dist.ini
          allow_dirty_match: []
          changelog: ''
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
      name: '@Author::BBYRD/@Git/Check'
      version: 2.036
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: 'Release v%v'
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - '.travis.yml'
            - README.pod
            - dist.ini
          allow_dirty_match: []
          changelog: ''
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::BBYRD/@Git/Commit'
      version: 2.036
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: ''
          signed: 0
          tag: v1.08
          tag_format: v%v
          tag_message: v%v
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::BBYRD/@Git/Tag'
      version: 2.036
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - 'origin master:master'
            - 'origin build/master:build/master'
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
      name: '@Author::BBYRD/@Git/Push'
      version: 2.036
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      config:
        Dist::Zilla::Plugin::GitHub::Update:
          metacpan: 1
      name: '@Author::BBYRD/GitHub::Update'
      version: 0.41
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::BBYRD/TestRelease'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::Travis::TestRelease
      name: '@Author::BBYRD/Travis::TestRelease'
      version: 1.15
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::BBYRD/ConfirmRelease'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::BBYRD/UploadToCPAN'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::BBYRD/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Clean
      name: '@Author::BBYRD/Clean'
      version: 0.07
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::BBYRD/::Role::BundleDeps'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::FileFinder::ByName
      name: NoOSMods
      version: 5.040
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugins:
            - '@Author::BBYRD'
          finder:
            - NoOSMods
          plugins:
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Author::BBYRD/SingleEncoding'
              version: 4.012
            -
              class: Pod::Weaver::Plugin::WikiDoc
              name: '@Author::BBYRD/WikiDoc'
              version: 0.093004
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: 4.012
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: 4.012
            -
              class: Pod::Weaver::Section::Name
              name: '@Author::BBYRD/Name'
              version: 4.012
            -
              class: Pod::Weaver::Section::Region
              name: '@Author::BBYRD/Prelude'
              version: 4.012
            -
              class: Pod::Weaver::Section::Generic
              name: '@Author::BBYRD/Synopsis'
              version: 4.012
            -
              class: Pod::Weaver::Section::Generic
              name: '@Author::BBYRD/Description'
              version: 4.012
            -
              class: Pod::Weaver::Section::Generic
              name: '@Author::BBYRD/Overview'
              version: 4.012
            -
              class: Pod::Weaver::Section::Collect
              name: Attributes
              version: 4.012
            -
              class: Pod::Weaver::Section::Collect
              name: Methods
              version: 4.012
            -
              class: Pod::Weaver::Section::Collect
              name: Functions
              version: 4.012
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Author::BBYRD/Leftovers'
              version: 4.012
            -
              class: Pod::Weaver::Section::Region
              name: '@Author::BBYRD/postlude'
              version: 4.012
            -
              class: Pod::Weaver::Section::Availability
              name: '@Author::BBYRD/Availability'
              version: 1.20
            -
              class: Pod::Weaver::Section::Support
              name: '@Author::BBYRD/Support'
              version: 1.007
            -
              class: Pod::Weaver::Section::Authors
              name: '@Author::BBYRD/Authors'
              version: 4.012
            -
              class: Pod::Weaver::Section::Contributors
              name: '@Author::BBYRD/Contributors'
              version: 0.009
            -
              class: Pod::Weaver::Section::Legal
              name: '@Author::BBYRD/Legal'
              version: 4.012
            -
              class: Pod::Weaver::Plugin::Transformer
              name: '@Author::BBYRD/List'
              version: 4.012
      name: PodWeaver
      version: 4.006
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Prereqs/AutoPrereqs'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Prereqs/MinimumPerl'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::MinimumPrereqs
      name: '@Prereqs/MinimumPrereqs'
      version: 0.93
    -
      class: Dist::Zilla::Plugin::PrereqsClean
      name: '@Prereqs/PrereqsClean'
      version: 0.93
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 5.040
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 5.040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: 5.040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::BBYRD/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: 5.040
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.040
x_authority: cpan:BBYRD
x_contributors:
  - "Chris 'BinGOs' Williams <chris@bingosnet.co.uk>"
  - 'Mithun Ayachit <m0t0rbr3th@gmail.com>'
